name: pub

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install NDK
        run: |
          cd ~
          wget -O NDK -q https://dl.google.com/android/repository/android-ndk-r15c-linux-x86_64.zip
          sudo apt install unzip -y
          unzip -q NDK
          ANDROID_NDK_HOME=$(pwd)/android-ndk-r15c
      - name: Build
        run: |
          sudo apt install gcc-multilib
          sudo chmod ugo+rwx -R ./
          ./make_android_luajit_arm64.sh
      - name: UploadJit
        uses: actions/upload-artifact@v2
        with:
          path: ./plugin_luajit/**/*
          name: plugin_luajit

  publish:
    runs-on: ubuntu-latest
    needs: [android]
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: plugin_luajit
          path: plugin_luajit/
          
      - uses: actions/download-artifact@v1
        with:
          name: plugin_lua53
          path: plugin_lua53/
          
      - uses: actions/download-artifact@v1
        with:
          name: plugin_lua54
          path: plugin_lua54/
          
      - name: Create Release Asset
        run: |
          cd plugin_luajit/ && tar cvfz ../luajit_master.tgz Plugins && cd -
          cd plugin_lua53/ && tar cvfz ../lua53_master.tgz Plugins && cd -
          cd plugin_lua54/ && tar cvfz ../lua54_master.tgz Plugins && cd -
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: master
          release_name: Tag:master
          draft: false
          prerelease: false
          
      - name: Upload luajit Plugins
        #id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./luajit_master.tgz
          asset_name: luajit_master.tgz
          asset_content_type: application/tgz
          
      - name: Upload lua53 Plugins
        #id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./lua53_master.tgz
          asset_name: lua53_master.tgz
          asset_content_type: application/tgz
          
      - name: Upload lua54 Plugins
        #id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./lua54_master.tgz
          asset_name: lua54_master.tgz
          asset_content_type: application/tgz
